ControlFocus("Open","","Edit1")
Sleep(3000)
ControlSetText("Open","","Edit1","D:\hchalla_Selenium\Super\KeywordDrivenFramework-master\src\main\java\KeywordDriven\Selenium\Data\UploaDocument.xlsx")
Sleep(3000)
ControlClick("Open","","Button1")
Sleep(3000)